services:
  - type: web
    name: youtube-channel-explorer
    env: node
    region: oregon
    plan: free
    buildCommand: "npm install"
    startCommand: "node app.js"
    envVars:
      - key: NODE_ENV
        value: production
